#include "../assets/languages/en-lang.pwn"
#include "../assets/defines/Colors.pwn"
#include "../assets/defines/DataBaseConnection.pwn"

#include "../assets/classes/DataBase.pwn"
#include "../assets/classes/Player.pwn"
#include "../assets/classes/Dialog.pwn"
#include "../assets/classes/Vehicle.pwn"
#include "../assets/classes/Object.pwn"
#include "../assets/classes/Pickup.pwn"